### ISSUE TITLE
Reduce image size if possible

### ISSUE THREAD

**Issue by xginn8** [balena-io-examples/balena-netdata#7]
~300Mb is too big to be useful, so let's trim the fat if we can.

**Comment by xginn8** [comment]
Related to https://github.com/netdata/netdata/issues/8805

**Comment by saintaardvark** [comment]
I've done some experiments on this, and here's what I've found so far.

Netdata supports [building a self-extracting binary](https://learn.netdata.cloud/docs/agent/packaging/makeself), at least for x86-64 platforms.  This worked without problems on my laptop.  I then put it into a Docker container like so:

```
FROM alpine:3.7 as build

ADD ./netdata-v1.22.1-282-g4a628fc0.gz.run /opt/
RUN chmod 755 /opt/netdata-v1.22.1-282-g4a628fc0.gz.run
RUN /opt/netdata-v1.22.1-282-g4a628fc0.gz.run --quiet --accept --noprogress --nox11
RUN rm /opt/netdata-v1.22.1-282-g4a628fc0.gz.run

FROM alpine:3.7 as run
# Hack to get the netdata user/group created by the install script
COPY --from=build /etc/passwd /etc/passwd
COPY --from=build /etc/group /etc/group
COPY --from=build /etc/shadow /etc/shadow
COPY --from=build /opt/netdata /opt/netdata
```

After that, I was able to run it like so:

```
	docker run \
		-p 19999:19999 \
		-it \
		-v netdatalib:/var/lib/netdata \
		-v netdatacache:/var/cache/netdata \
		-v /etc/passwd:/host/etc/passwd:ro \
		-v /etc/group:/host/etc/group:ro \
		-v /proc:/host/proc:ro \
		-v /sys:/host/sys:ro \
		-v /etc/os-release:/host/etc/os-release:ro \
		--restart unless-stopped \
		--cap-add SYS_PTRACE \
		--security-opt apparmor=unconfined \
		--name netdata-smol \
		netdata-smol:latest \
		/opt/netdata/bin/netdata -D
```

Not the greatest way of building it, of course, but it gave me a way to get some quick comparisons.

Image size is less than 30% of the original; `netdata-smol` is the image I built:

```
staging 🐋)|Tue Jun 16 13:24:40|[linux:~/dev/src/github.com/netdata/netdata]$ docker images | grep netdata
netdata-smol                             latest              e1da011ff2af        3 minutes ago       88.7MB
netdata/netdata                          latest              2aae1c80d6ca        20 hours ago        307MB
```

A quick look at the dashboard running within that container (again, just on my laptop) shows a reasonable approximation of what we see when running the upstream image on a Raspberry Pi:

![image](https://user-images.githubusercontent.com/1486793/84825889-fe263380-afd6-11ea-94e2-79bdae37839b.png)

I'm assuming for now that the differences (no containers, no wifi, etc) are due to the way I'm running it, but I haven't verified that.

Unanswered questions:

- What's the build process for other devices?

- Is the dashboard we'd see on a self-built container the same as we'd see using an upstream container?  If not, is it still acceptable?

- Is ~ 90MB acceptable for an image size?  If not, what's our target?

One thing to note about [the upstream issue](https://github.com/netdata/netdata/issues/8805) is that the proposed solution is downloading plugins based on user preference.  That seems less than ideal for bandwidth-limited devices, so I imagine we'd need to still think about packaging our own version if this was adopted.

**Comment by saintaardvark** [comment]
Another approach is to use the already-existing (though still in `edge/testing`) packages from Alpine Linux.  I'm working on this under the branch `netdata-smol`.  Initial results are quite promising; the image size is ~ 20MB, and seems quite similar to upstream's default dashboard.

**Comment by saintaardvark** [comment]
The `netdata-smol` branch seems to be working pretty well.  

We do have to create `/var/lib/netdata`; I've filed a bug for this [upstream](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11678), and apparently this is created by OpenRC, which they use to supervise this.  I've made our case, but the workaround if they turn it down is pretty trivial.
